version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang:1.11.4
    volumes:
      - ./:/go/src/github.com/NasSilverBullet/auto_insert_timestamps_on_teamsprit
